on:
  release:
    types: [created]
name: Handle Release
jobs:
  generate:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.x'
      - name: Generate templ artifacts
        run: go install github.com/a-h/templ/cmd/templ@latest && templ generate

      - name: Build linux
        run: env GOOS=linux GOARCH=amd64 go build -o just-linux-amd64 && env GOOS=linux GOARCH=386 go build -o just-linux-386

      - name: Build windows
        run: env GOOS=windows GOARCH=amd64 go build -o just-windows-amd64.exe && env GOOS=windows GOARCH=386 go build -o just-windows-386.exe

      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'just-*'
